trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
        imageName: 'quay.io/fatherlinux/ubi-azure-pipelines-build'
        serviceConnection: 'quayServiceConnection'

steps:
- task: Docker@2
  displayName: Build from Red Hat Universal Base Image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile-build
    tags: latest
- task: Docker@2
  displayName: Push image to quay.io
  inputs:
    repository: $(imageName)
    command: push
    tags: latest
