trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'quay.io/fatherlinux/ubi-azure-pipelines-build'

steps:
- task: Docker@2
  displayName: Build from Red Hat Universal Base Image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
